[package]
name = "p4runtime-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["examples/basic"]

[dependencies]
anyhow = "1.0.83"
# p4runtime = { path = "../p4runtime/rust" }
p4runtime = { git = "https://github.com/duskmoon314/p4runtime", branch = "rust" }
prost = "0.12.4"
serde = { version = "1.0.201", features = ["derive"] }
thiserror = "1.0.60"
tokio = { version = "1.37.0", features = ["sync"] }
tokio-stream = "0.1.15"
tonic = "0.11.0"
